import { ComponentStats, AnalyzerOptions, TranslatePipeUsage } from './types';
export declare class AngularComponentAnalyzer {
    private options;
    private ngProgram;
    private components;
    private selectorToComponent;
    private templateUsages;
    private translatePipeUsages;
    private projectPath;
    constructor(options: AnalyzerOptions);
    private findTsConfig;
    analyze(): Promise<ComponentStats[]>;
    private discoverComponentsFromCompiler;
    private visitSourceFile;
    private processComponent;
    private parseTemplates;
    private getComponentTemplate;
    private analyzeTemplate;
    private walkTemplateNodes;
    private detectTranslatePipeInNode;
    private detectTranslatePipeInExpression;
    private aggregateResults;
    private isAngularBuiltin;
    private isExternal;
    private guessLibrarySource;
    private determineSource;
    getTranslatePipeUsages(): TranslatePipeUsage[];
}
export declare function analyzeComponents(options: AnalyzerOptions): Promise<ComponentStats[]>;
export declare function analyzeTranslatePipes(options: AnalyzerOptions): Promise<TranslatePipeUsage[]>;
